export const API_ROUTES = {
  HEALTH: '/health',
  CHARACTER: '/character',
  QUESTS: '/quests',
  QUEST_COMPLETION: '/quest-completion',
  PROGRESSION: '/progression',
  STREAK: '/streak',
  STREAK_CALENDAR: '/streak/calendar',
  STREAK_RECOVER: '/streak/recover',
  QUEST_CHAINS: '/quest-chains',
  ATTRIBUTES: '/character/attributes',
  EVOLUTION: '/character/evolution',
  SKILL_TREE: '/skill-tree',
  SKILL_TREE_UNLOCK: '/skill-tree/unlock',
  BOSS_QUESTS: '/boss-quests',
  BOSS_OBJECTIVES: '/boss-quests/:bossId/objectives',
  BOSS_LINK_QUEST: '/boss-quests/:bossId/link-quest',
  SHOP: '/shop',
  SHOP_ITEM: '/shop/:itemId',
  SHOP_PURCHASE: '/shop/:itemId/purchase',
  ECONOMY_TRANSACTIONS: '/economy/transactions',
  REWARDS: '/rewards',
  INVENTORY: '/inventory',
  INVENTORY_ITEM: '/inventory/:itemId',
  INVENTORY_EQUIP: '/inventory/:itemId/equip',
  INVENTORY_UNEQUIP: '/inventory/:itemId/unequip',
  CHARACTER_EQUIPMENT: '/character/equipment',
  ACHIEVEMENTS: '/achievements',
  ACHIEVEMENT_DETAIL: '/achievements/:achievementId',
  ACHIEVEMENTS_SUMMARY: '/achievements/summary',
} as const;

export const DEFAULT_PORTS = {
  FRONTEND: 3000,
  BACKEND: 4000,
} as const;
