import type { SkillNode } from '../types/skill';

export const SKILL_NODES: SkillNode[] = [
  // STRENGTH
  {
    id: 'str_t1_endurance',
    attributeKey: 'STRENGTH',
    tier: 1,
    title: 'Endurance Engine',
    description: 'Optimize metabolic stamina, physical recovery, and baseline vitality.',
    spCost: 1,
    requiredAttributeLevel: 1,
    prerequisiteSkillId: null,
    iconName: 'Heart',
    perkEffect: '+5% XP gained on Health quests',
  },
  {
    id: 'str_t2_iron_will',
    attributeKey: 'STRENGTH',
    tier: 2,
    title: 'Iron Will',
    description: 'Imbue physical discipline with unwavering mental stamina against fatigue.',
    spCost: 1,
    requiredAttributeLevel: 2,
    prerequisiteSkillId: 'str_t1_endurance',
    iconName: 'Shield',
    perkEffect: 'Reinforces streak consistency and athletic habit resilience',
  },
  {
    id: 'str_t3_peak_performance',
    attributeKey: 'STRENGTH',
    tier: 3,
    title: 'Peak Performance',
    description: 'Achieve physiological mastery and relentless daily energy.',
    spCost: 2,
    requiredAttributeLevel: 4,
    prerequisiteSkillId: 'str_t2_iron_will',
    iconName: 'Flame',
    perkEffect: 'Unlocks Vitality Mastery title and radiant golden aura',
  },

  // INTELLIGENCE
  {
    id: 'int_t1_comprehension',
    attributeKey: 'INTELLIGENCE',
    tier: 1,
    title: 'Deep Comprehension',
    description: 'Absorb technical concepts and mental models with high retention.',
    spCost: 1,
    requiredAttributeLevel: 1,
    prerequisiteSkillId: null,
    iconName: 'BookOpen',
    perkEffect: '+5% XP gained on Learning quests',
  },
  {
    id: 'int_t2_velocity',
    attributeKey: 'INTELLIGENCE',
    tier: 2,
    title: 'Cognitive Velocity',
    description: 'Accelerate reading speed, problem synthesis, and complex analysis.',
    spCost: 1,
    requiredAttributeLevel: 2,
    prerequisiteSkillId: 'int_t1_comprehension',
    iconName: 'Brain',
    perkEffect: 'Multiplies XP bonus when completing consecutive learning quests',
  },
  {
    id: 'int_t3_omniscience',
    attributeKey: 'INTELLIGENCE',
    tier: 3,
    title: 'Omniscience',
    description: 'Master multidisciplinary synthesis and expansive intellectual acuity.',
    spCost: 2,
    requiredAttributeLevel: 4,
    prerequisiteSkillId: 'int_t2_velocity',
    iconName: 'Sparkles',
    perkEffect: 'Unlocks Arcanist Luminary title and celestial intellect glow',
  },

  // DISCIPLINE
  {
    id: 'dis_t1_hyperfocus',
    attributeKey: 'DISCIPLINE',
    tier: 1,
    title: 'Hyperfocus',
    description: 'Eliminate task friction and enter flow state on command.',
    spCost: 1,
    requiredAttributeLevel: 1,
    prerequisiteSkillId: null,
    iconName: 'Target',
    perkEffect: '+5% XP gained on Career quests',
  },
  {
    id: 'dis_t2_cadence',
    attributeKey: 'DISCIPLINE',
    tier: 2,
    title: 'Unbreakable Cadence',
    description: 'Maintain execution rhythm across multi-day professional milestones.',
    spCost: 1,
    requiredAttributeLevel: 2,
    prerequisiteSkillId: 'dis_t1_hyperfocus',
    iconName: 'Briefcase',
    perkEffect: 'Accelerates Quest Chain step progression momentum',
  },
  {
    id: 'dis_t3_titan',
    attributeKey: 'DISCIPLINE',
    tier: 3,
    title: 'Titan of Industry',
    description: 'Execute massive strategic projects with executive presence.',
    spCost: 2,
    requiredAttributeLevel: 4,
    prerequisiteSkillId: 'dis_t2_cadence',
    iconName: 'Hammer',
    perkEffect: 'Unlocks Commander of Execution title and forged steel frame',
  },

  // WISDOM
  {
    id: 'wis_t1_frugality',
    attributeKey: 'WISDOM',
    tier: 1,
    title: 'Calculated Frugality',
    description: 'Optimize resource allocation and cultivate long-range financial restraint.',
    spCost: 1,
    requiredAttributeLevel: 1,
    prerequisiteSkillId: null,
    iconName: 'Scale',
    perkEffect: '+5% XP gained on Finance quests',
  },
  {
    id: 'wis_t2_compound',
    attributeKey: 'WISDOM',
    tier: 2,
    title: 'Compound Advantage',
    description: 'Harness exponential returns on financial savings and strategic assets.',
    spCost: 1,
    requiredAttributeLevel: 2,
    prerequisiteSkillId: 'wis_t1_frugality',
    iconName: 'Coins',
    perkEffect: 'Awards bonus multipliers for sustained financial planning streaks',
  },
  {
    id: 'wis_t3_sovereign',
    attributeKey: 'WISDOM',
    tier: 3,
    title: 'Sovereign Wealth',
    description: 'Attain profound fiscal sovereignty and legacy generational security.',
    spCost: 2,
    requiredAttributeLevel: 4,
    prerequisiteSkillId: 'wis_t2_compound',
    iconName: 'Sparkles',
    perkEffect: 'Unlocks Grand Sovereign title and gilded imperial aura',
  },

  // CREATIVITY
  {
    id: 'crt_t1_spark',
    attributeKey: 'CREATIVITY',
    tier: 1,
    title: 'Lateral Spark',
    description: 'Generate non-obvious solutions and expressive artistic concepts.',
    spCost: 1,
    requiredAttributeLevel: 1,
    prerequisiteSkillId: null,
    iconName: 'Lightbulb',
    perkEffect: '+5% XP gained on Creativity quests',
  },
  {
    id: 'crt_t2_polymath',
    attributeKey: 'CREATIVITY',
    tier: 2,
    title: 'Polymath Flow',
    description: 'Bridge disparate domains into cohesive designs, narratives, and inventions.',
    spCost: 1,
    requiredAttributeLevel: 2,
    prerequisiteSkillId: 'crt_t1_spark',
    iconName: 'Palette',
    perkEffect: 'Grants XP synergy bonus when completing quests across diverse categories',
  },
  {
    id: 'crt_t3_architect',
    attributeKey: 'CREATIVITY',
    tier: 3,
    title: 'Master Architect',
    description: 'Translate pure imagination into lasting, influential real-world creations.',
    spCost: 2,
    requiredAttributeLevel: 4,
    prerequisiteSkillId: 'crt_t2_polymath',
    iconName: 'Sparkles',
    perkEffect: 'Unlocks Visionary Luminary title and prism chromatic aura',
  },

  // RESILIENCE
  {
    id: 'res_t1_fortress',
    attributeKey: 'RESILIENCE',
    tier: 1,
    title: 'Mindful Fortress',
    description: 'Anchor inner serenity, reduce stress, and maintain clear perspective.',
    spCost: 1,
    requiredAttributeLevel: 1,
    prerequisiteSkillId: null,
    iconName: 'Shield',
    perkEffect: '+5% XP gained on Personal quests',
  },
  {
    id: 'res_t2_equilibrium',
    attributeKey: 'RESILIENCE',
    tier: 2,
    title: 'Inner Equilibrium',
    description: 'Recover swiftly from adversity, burnout, or emotional turbulence.',
    spCost: 1,
    requiredAttributeLevel: 2,
    prerequisiteSkillId: 'res_t1_fortress',
    iconName: 'Heart',
    perkEffect: 'Shields mental focus against productivity dips and resets',
  },
  {
    id: 'res_t3_harmony',
    attributeKey: 'RESILIENCE',
    tier: 3,
    title: 'Ascended Harmony',
    description: 'Radiate grounded wisdom, unshakeable composure, and holistic balance.',
    spCost: 2,
    requiredAttributeLevel: 4,
    prerequisiteSkillId: 'res_t2_equilibrium',
    iconName: 'Sparkles',
    perkEffect: 'Unlocks Zen Warden title and soothing emerald aura',
  },
];

export function getSkillById(id: string): SkillNode | undefined {
  return SKILL_NODES.find((s) => s.id === id);
}

export function getSkillsByAttribute(attributeKey: string): SkillNode[] {
  return SKILL_NODES.filter((s) => s.attributeKey === attributeKey);
}
